### ISSUE TITLE
Cannot generate expectations for aggregate_of covariates

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/cohort-extractor#404]
The following test fails:

```
def test_make_df_from_expectations_with_minimum_of():
    study = StudyDefinition(
        population=patients.all(),
        a=patients.with_these_clinical_events(
            codelist(["A"], system="ctv3"),
            returning="numeric_value",
            find_first_match_in_period=True,
            return_expectations={
                "incidence": 0.2,
                "float": {"distribution": "normal", "mean": 60.0, "stddev": 60},
                "date": {"earliest": "2020-01-01", "latest": "2020-01-11"},
            },
        ),
        b=patients.with_these_clinical_events(
            codelist(["B"], system="ctv3"),
            returning="numeric_value",
            find_first_match_in_period=True,
            return_expectations={
                "incidence": 0.2,
                "float": {"distribution": "normal", "mean": 60.0, "stddev": 60},
                "date": {"earliest": "2020-01-01", "latest": "2020-01-11"},
            },
        ),
        m=patients.minimum_of(
            "a",
            "b",
            return_expectations={
                "incidence": 0.2,
                "float": {"distribution": "normal", "mean": 60.0, "stddev": 60},
                "date": {"earliest": "2020-01-01", "latest": "2020-01-11"},
            },
        ),
    )
    population_size = 10
    result = study.make_df_from_expectations(population_size)
    print(result)
```

It fails with:

```
$ pytest --tb=native -s tests/test_expectation_generators.py::test_make_df_from_expectations_with_minimum_of
======================================== test session starts ========================================
platform linux -- Python 3.8.2, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/inglesp/work/ebmdatalab/opensafely/cohort-extractor
plugins: freezegun-0.4.2
collected 1 item                                                                                    

tests/test_expectation_generators.py F

============================================= FAILURES ==============================================
__________________________ test_make_df_from_expectations_with_minimum_of ___________________________
Traceback (most recent call last):
  File "/home/inglesp/work/ebmdatalab/opensafely/cohort-extractor/tests/test_expectation_generators.py", line 824, in test_make_df_from_expectations_with_minimum_of
    study = StudyDefinition(
  File "/home/inglesp/work/ebmdatalab/opensafely/cohort-extractor/cohortextractor/study_definition.py", line 26, in __init__
    self._original_covariates = process_covariate_definitions(covariates)
  File "/home/inglesp/work/ebmdatalab/opensafely/cohort-extractor/cohortextractor/process_covariate_definitions.py", line 12, in process_covariate_definitions
    covariate_definitions = flatten_nested_covariates(covariate_definitions)
  File "/home/inglesp/work/ebmdatalab/opensafely/cohort-extractor/cohortextractor/process_covariate_definitions.py", line 40, in flatten_nested_covariates
    name, (query_type, query_args) = items.pop(0)
ValueError: too many values to unpack (expected 2)
====================================== short test summary info ======================================
FAILED tests/test_expectation_generators.py::test_make_df_from_expectations_with_minimum_of - Valu...
========================================= 1 failed in 0.47s =========================================

```

This is because `patients.minimum_of()` doesn't do anything special with `return_expectations`:

```
def minimum_of(*column_names, **extra_columns):
    aggregate_function = "MIN"
    column_names = column_names + tuple(extra_columns.keys())
    return "aggregate_of", locals()
```

I changed the signature to `minimum_of(*column_names, return_expectations=None, date_format=None, **extra_columns)`, and the test now passes.

But for date expressions it only generates years.  So

```
    study = StudyDefinition(
        population=patients.all(),
        a=patients.with_these_clinical_events(
            codelist(["A"], system="ctv3"),
            return_first_date_in_period=True,
            return_expectations={
                "incidence": 0.2,
                "date": {"earliest": "2020-02-01", "latest": "2021-02-01"},
            },
        ),
        b=patients.with_these_clinical_events(
            codelist(["B"], system="ctv3"),
            return_first_date_in_period=True,
            return_expectations={
                "incidence": 0.2,
                "date": {"earliest": "2020-02-01", "latest": "2021-02-01"},
            },
        ),
        m=patients.minimum_of(
            "a",
            "b",
            return_expectations={
                "incidence": 0.2,
                "date": {"earliest": "2020-02-01", "latest": "2021-02-01"},
            },
        ),
    )
```

generates eg

```
a     b     m
0   NaN   NaN   NaN
1  2021   NaN  2021
2   NaN   NaN   NaN
3   NaN  2020   NaN
4   NaN   NaN   NaN
5   NaN   NaN   NaN
6   NaN  2020   NaN
7   NaN   NaN  2020
8   NaN   NaN   NaN
9  2020   NaN   NaN
```

Adding a `date_format` parameter to `patients.minimum_of` doesn't work, and fails unsurprisingly with `TypeError: get_aggregate_expression() got an unexpected keyword argument 'date_format'`.

Fixing this might be quite involved, and we should maybe focus efforts on #359.

**Comment by annaschultze** [comment]
+1 on this being a useful functionality, currently attempting to create variables relative to a date which is a minimum of two other dates. I'll do this in Stata in the meantime. For reference, I ran this code


```
    ## any
    any_vte_gp=patients.with_these_clinical_events(
        vte_codes_primary_care,
        returning="date", 
        date_format="YYYY-MM-DD",
        on_or_after="index_date",
        find_first_match_in_period=True,
        return_expectations={"date": {"earliest": "index_date"}},
    ),
    any_vte_hospital=patients.admitted_to_hospital(
        with_these_diagnoses=vte_codes_secondary_care,
        on_or_after="index_date",
        date_format="YYYY-MM-DD",
        find_first_match_in_period=True,
        return_expectations={"date": {"earliest": "index_date"}},
    ), 

any_vte_date==patients.minimum_of("any_vte_gp", "any_vte_hospital"),
```
which failed with this error message 
```
     File "/app/cohortextractor/process_covariate_definitions.py", line 407, in type_of_aggregate_of
         raise ValueError(
     ValueError: Cannot calculate MIN over columns of different types (found 'bool' and 'date')
``` 
(I realise this sounds like a different error, but there's no return=date functionality in patients.admitted_to_hospital, and it outputs dates when run without this, so think it's part of the patients.minimum_of functionality as well).

**Comment by evansd** [comment]
@annaschultze I think there are actually several problems going on at once here! `admitted_to_hospital` supports `date_admitted` and `date_discharged` but not `date` as `returning` options (because of the risk of ambiguity). So you will need to specify one of those, otherwise you get the default `binary_flag` type. However there's currently nothing that validates that the type supplied in `return_expectations` matches the real type and so that's why it _looks_ like it still returns a date anyway.

If you fix that then that specific "Cannot calculate MIN over columns of different types" error will go away, but you'll still hit the original problem specified in this ticket so it won't actually get you that far.

I am looking at this again now. Doing it properly is a big job that really needs to be done alongside a whole other set of changes, but it might be there's something simpler we can do to fix it for now.

**Comment by annaschultze** [comment]
Hi @evansd sorry I missed your response! I also realised I'd forgotten a `returning="date_admitted"` statement for that variable, sorry. I'll update and see how I get on.
