### ISSUE TITLE
Error generating categorical variables

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/cohort-extractor#627]
Generating categorical variables (I presume) is throwing [this error](https://github.com/opensafely/long-covid/runs/3219046467).  I have also seen this [here](https://github.com/opensafely/SRO-Measures/runs/3172682127). This is potentially related to #622.

**Comment by evansd** [comment]
Just copying the relevant bit of the error logs:
```
2021-08-02 09:10:12 [info     ] Generating cohort for study_definition_cohort in output [cohortextractor.cohortextractor] 
     Exception at 2021-08-02 09:10:15 UTC
     Traceback (most recent call last):
       File "/usr/local/bin/cohortextractor", line 33, in <module>
         sys.exit(load_entry_point('opensafely-cohort-extractor', 'console_scripts', 'cohortextractor')())
       File "/app/cohortextractor/cohortextractor.py", line 668, in main
         generate_cohort(
       File "/app/cohortextractor/cohortextractor.py", line 151, in generate_cohort
         _generate_cohort(
       File "/app/cohortextractor/cohortextractor.py", line 202, in _generate_cohort
         study.to_file(
       File "/app/cohortextractor/study_definition.py", line 83, in to_file
         df = dataframe_from_rows(
       File "/app/cohortextractor/pandas_utils.py", line 63, in dataframe_from_rows
         categorical = pandas.Categorical.from_codes(
       File "/usr/local/lib/python3.8/dist-packages/pandas/core/arrays/categorical.py", line 637, in from_codes
         dtype = CategoricalDtype._from_values_or_dtype(
       File "/usr/local/lib/python3.8/dist-packages/pandas/core/dtypes/dtypes.py", line 330, in _from_values_or_dtype
         dtype = CategoricalDtype(categories, ordered)
       File "/usr/local/lib/python3.8/dist-packages/pandas/core/dtypes/dtypes.py", line 222, in __init__
         self._finalize(categories, ordered, fastpath=False)
       File "/usr/local/lib/python3.8/dist-packages/pandas/core/dtypes/dtypes.py", line 369, in _finalize
         categories = self.validate_categories(categories, fastpath=fastpath)
       File "/usr/local/lib/python3.8/dist-packages/pandas/core/dtypes/dtypes.py", line 543, in validate_categories
         raise ValueError("Categorial categories cannot be null")
     ValueError: Categorial categories cannot be null
```

And these were the commits of the runs which triggered those errors:
https://github.com/opensafely/long-covid/commit/7f45e9f3f9da00ad89b9ea4648e488cd7d73622c
https://github.com/opensafely/SRO-Measures/commit/bcfbc1f81afa38cc9afb3d93852d946c9f7500a8

**Comment by wjchulme** [comment]
Same issue in a different repo.

This study definition: https://github.com/opensafely/comparative-ve-research/blob/6b396a7e168543e9a818e8d9f65b19468050b8d4/analysis/study_definition.py

worked prior to / failed after this commit: https://github.com/opensafely-core/cohort-extractor/commit/af65defb1ed92441f6c761bbfc8dce68409ccf0a#diff-10a0cd05b4e74b4480089a8edd91ff20d68a0c20c169e291f0a6acca1b00b362R77

Error here: https://github.com/opensafely/comparative-ve-research/runs/3175130779
